# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9.x'
    addToPath: true
    architecture: 'x64'
- task: PipAuthenticate@1
  inputs:
    onlyAddExtraIndex: true
- task: CmdLine@2
  inputs:
    script: 'pip install paconn'
- task: CmdLine@2
  inputs:
    script: 'paconn login'